### ISSUE TITLE
Allow deactivation of account - readonly account

### ISSUE THREAD

**Issue by Tobisaninfo** [deadlocker8/BudgetMaster#528]
- Read only account (transactions can't be edited nor deleted)
- In transfer or transaction: don't show in account select

## Tasks
- [x] add new field "isReadOnly" to account
- [x] allow to set an account as readonly/readable
- [x] hide readonly accounts from account select (new transaction page)
- [x] prevent deletion of transactions with readonly account
- [x] prevent editing of transactions with readonly account
- [x] prevent addition of transactions for readonly account
- [x] readonly accounts should not be selectable as default account
- [x] default account should not be able to set to readonly
- [x] handle templates pointing to readonly account
- [x] integration tests

**Comment by deadlocker8** [comment]
- [ ] add new field "isReadOnly" to account
- [ ] allow to set an account as readonly/readable
- [ ] hide readonly accounts from account select (new transaction page)
- [ ] prevent deletion of transactions with readonly account
- [ ] prevent editing of transactions with readonly account
- [ ] prevent addition of transactions for readonly account
