### ISSUE TITLE
warn about income/expenditure switch if certain keywords are in transaction name

### ISSUE THREAD

**Issue by deadlocker8** [deadlocker8/BudgetMaster#677]
Example: "Refund" --> ask, whether this transaction should be marked as income and the user simply forgot to select the switch

## TODO
- [x] design warning (popup that prevents saving)
- [x] show warning if keyword is in transaction name
- [x] allow personalization of keywords in settings
  - [x] use chips input
  - [x] new entity for keywords
    - [x] adapt import/export mechanism
    - [x] ~~adapt migrator~~ --> nothing to do
- [x] link to settings in warning
- [x] tests
- [x] check for transaction names in templates too
- [x] define default keyword list 

## default keywords
- einnahme
- rückzahlung
- erstattung
- zinsen
- lohn
- gehalt
-
